project_name: til
builds:
  - id: til
    binary: til
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
brews:
  - name: til
    repository:
      owner: ff6347
      name: homebrew-tap
      token: "{{ .Env.BREWTAP_TOKEN }}"
    commit_author:
      name: Fabian Morón Zirfas
      email: hash@ff6347.email
    homepage: https://github.com/ff6347/til
    description: til (today I learned) CLI
    license: MIT
    install: |
      bin.install "til"
